### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by nantas** [fireball-x/firedoc-theme-notab#1]
和 firedoc 默认主题相比，更改/增加了以下功能：
- [x] 左边导航栏分级显示内容，module->class->member list
- [x] 左边导航栏的 scroll 和 正文的 scroll 分开
- [x] 支持统一搜索. 比如 Fire.log, 可以搜索出 Fire 底下的 log member
- [x] 更好的样式标签显示和配色

参考 pixi 的新文档：http://pixijs.github.io/docs/
github：https://github.com/davidshimjs/jaguarjs-jsdoc

**Comment by jwu** [comment]
另外一个关于 Fireball API 文档增强可读性的建议:

我觉得分级显示应该只有 Module 和 Member 而不应该如 @nantas 所说的 Module -> Class -> Member List. 

Module  这一项实际上包括了 Module, Class, Static Namespace ( concept from jsdoc). 
Member 这一项包括了 Member, Properties, Method

显示出来的效果如图:

![screen shot 2015-05-25 at 4 00 04 pm](https://cloud.githubusercontent.com/assets/174891/7793904/86c80cdc-02f7-11e5-887b-538e9dde3eef.png)

显示的时候, 也希望能够以 a.b.c 的形式. 在 Fireball 的 API 中, 左边导航栏中显示采用 `@Module` 的形式, 导致了 API 辨识度较低, 不能很快的将 Sprite 和 Fire.Sprite 产生联系.

**Comment by yorkie** [comment]
@jwu 如果以命名空间的方式，超过默认长度的时候应该优先切割前面部分还是后面部分？

**Comment by jwu** [comment]
后面部分, just css it as:

``` css
    overflow: hidden
    text-overflow: ellipsis
```

**Comment by yorkie** [comment]
Okay, Got it

**Comment by yorkie** [comment]
> 左边导航栏分级显示内容，module->class->member list

@nantas @jwu 这里需要你们给一个最终的结果，是按照谁的方案来做，谢谢。

> 我觉得分级显示应该只有 Module 和 Member 而不应该如 @nantas 所说的 Module -> Class -> Member List.

@jwu 这里的Module"和“Member的“和”字代表的具体是什么？表示Module和Member是同级还是module>member的意思？

> 支持统一搜索. 比如 Fire.log, 可以搜索出 Fire 底下的 log member

如果搜索的内容在左侧导航列表中，就可以实现，但是不能搜索列表中不存在的选项。

**Comment by jwu** [comment]
这里 module 和 member 应该是分级的关系, module > member. 这里 module 定义有些混乱, 我用例子来说明一下:

这些算 module:

```
Editor (他是一个 static class)
Editor.JS  (他是一个 static class)
Editor.Packages (他是一个 static class)
Editor.Menu (他是一个 class)
```

这些算 member:

```
Editor.JS.addon
Editor.JS.clear
Editor.JS.extract
Editor.Packages.load
...
```

我不知道这样的分类是否符合目前 fire-doc 的书写标准.

**Comment by yorkie** [comment]
意思是去掉class吗？

**Comment by nantas** [comment]
意思是 class 和 module 平行排列，以搜索为主而不是以浏览为主来检索左侧内容。
module 和 class 的成员显示方法一致，就是图中的小字，这样的话由 module/class->member 两级显示可读性会强一些。

**Comment by yorkie** [comment]
懂了，那如何处理module下的class，是把class都拉到一级菜单还是说继续保持在module中，另外enum类怎么处理，跟class同等对待吗？

**Comment by nantas** [comment]
class都拉到最上层，enum 也是拉到最上层

我们可以扩展上图中的标签显示，这样 module，class，enum 都有自己的标签，看起来比较清楚

**Comment by yorkie** [comment]
ok 明白了 另外还有一个问题，因为module class enum都被放在同一级显示了，所以排序是一个问题，我这里有两种方案：
1. 全部按照字典序排
2. 按照module class enum分组，然后每一组各自按照字典序排列，这里他们仍然是在同一级

我个人偏向于后一种，可能看起来会好看一些，所以我先按第二种做，如果觉得有问题，我再改

**Comment by nantas** [comment]
ok

**Comment by yorkie** [comment]
@nantas @jwu 前三个已完成，可以在 http://fireball-x.github.io/firedoc/en 看看是否有错，谢谢了

**Comment by yorkie** [comment]
http://fireball-x.github.io/firedoc/en/modules/yuidoc.html 我大概改了下样式 其实也没怎么改 你们看下 还有需要改的 你们告诉我

**Comment by jwu** [comment]
目前搜索栏是 confirm 后才进行搜索的, 是否能够做成 debounce ( on-input )?

**Comment by yorkie** [comment]
好 我试试

**Comment by yorkie** [comment]
已更新了 http://fireball-x.github.io/firedoc/en/
好建议 体验比原来要好很多 :)

**Comment by nantas** [comment]
这个测试页面的主题可以下载了吗？我想用 fireball 0.4 的api 数据测试

**Comment by yorkie** [comment]
可以的 直接按照 https://github.com/fireball-x/firedoc-theme-notab#安装 给的提示安装就可以 然后他会自动把主题安装了本地的firedoc/themes的目录下，然后通过`--theme firedoc-theme-notab`使用就可以了，但是firedoc更新版本以后需要重新下载。

**Comment by nantas** [comment]
新主题在 Fireball 0.4版的预览：
http://docs.fireball-x.com/api/

目前问题：
- [x] 左侧导航栏排序混乱，似乎不是按照alphabet
- [x] 点击左侧导航栏条目时，内容过多时展开会被截断（下图1）
- [x] 搜索时应该优先排序 module/class/enum 等一级内容，然后再匹配 member/method 等二级内容
- [x] 按`s`键可以激活搜索栏的功能没有了
- [x] [valuetype](http://docs.fireball-x.com/api/classes/ValueType.html)里出现大量冗余`<p>`tag。
- [x] [Fire.Color](http://docs.fireball-x.com/api/classes/Color.html) 里 inherit members 这一节没有内容，只有标题
- [x] 左侧导航栏点击条目切换页面时，右边的内容页应该 scroll 回 top 位置

![fire_js](https://cloud.githubusercontent.com/assets/344547/8177367/912ba5e4-1436-11e5-802c-ab23d78be15f.png)

api正文样式的改善另开 issue。

**Comment by yorkie** [comment]
好！！！

**Comment by nantas** [comment]
楼上又补充了一些问题~

**Comment by yorkie** [comment]
更新完成，可以用最新的再试试，另外只有第二点我不是太明白：

> 搜索时应该优先排序 module/class/enum 等一级内容，然后再匹配 member/method 等二级内容

我现在的逻辑只是把所有的name匹配的显示出来，如果第二级（members）匹配成功，但是第一级没有，第一级也会显示出来。另外我强制型地如果是搜索列表的话，会“展开”所有的二级菜单。

我想 @nantas 的意思是不是：如果只是module/class/enum等匹配，但是members没有匹配的就把二级菜单“收起”是这样吗？

**Comment by nantas** [comment]
比如说我搜索"transform" 时，排在前面几个的都是一些 class 里的`transform` property，但如果有完全 match 的 class `Transform`，我认为根据用户需要应该排在最前面显示这个 class。

并不是把二级菜单收起，而是把第一级的 match 排在前面，把第二级的 match 放在下面

**Comment by yorkie** [comment]
明白了 会照做

**Comment by yorkie** [comment]
@nantas 已修复所有checkbox，也需要更新firedoc
