### ISSUE TITLE
Class and enum name not displayed in left sidebar

### ISSUE THREAD

**Issue by nantas** [fireball-x/firedoc-theme-notab#3]
Tested in firedoc v1.5.10

![image](https://cloud.githubusercontent.com/assets/344547/8267124/396be1ee-1787-11e5-9ede-e1b2ed709b78.png)

as showed in picture, the class and enum title is empty.

**Comment by yorkie** [comment]
To reproduce what happened, I also need the document source, could you send me at bearyChat, thank you @nantas :)

**Comment by yorkie** [comment]
This should be a bug from firedoc, and it got fixed at https://github.com/fireball-x/firedoc/commit/cec14dcdbfedd0ca491adbcc9dbc0761fc12184e and `firedoc@1.5.11`
