### ISSUE TITLE
When build in local mode, links in sidebar will be absolute so it doesn't work on a different machine

### ISSUE THREAD

**Issue by nantas** [fireball-x/firedoc-theme-notab#9]
If use relative path in sidebar links, open a file in a sub folder will cause relative path to be invalid:

`href='./modules/my_page.html'` works for `index.html`, but in `modules/my_page.html`, the link will be `modules/modules/my_page.html`

**Comment by yorkie** [comment]
@nantas how about integrating a tiny server with the generated files? Actually I created a file server https://github.com/yorkie/serve which is only 140KB and most importantly, it doesn't require any runtime.

So that we can remove the local mode, and use HTTP anywhere, the file protocol really sucks on us, isn't it :-)

**Comment by nantas** [comment]
it would be great if we can get around http server so that we can create api docs that are portable and can be opened anywhere.

Just need to figure out how to get each page's path when rendering template.

**Comment by nantas** [comment]
It works great for viewing pages locally, but I found a glitch when access generated website. To reproduce:
1. First complete `firedoc build` (I believe `--http` option is not relevant now, correct?)
2. start a http server in output directory
3. open the index page of the website, eg: `localhost:8000/index.html`
4. Click on any module or class link in left sidebar, now the main page has updated with your module or class information.
5. But the links in left sidebar are not updated. Now when you inspect the same module/class link you'll see `./modules/MyModule.html` as in root level pages, insead of `../modules/MyModule.html`
6. If you refresh the web page, all links will be correct. If you jump from one module page to another it's also good.

So what happened when user jump from index page to a module page? Why the link is not updated?

**Comment by nantas** [comment]
Another issue, `../base` works fine for page level links such as modules and classes: https://github.com/fireball-x/firedoc-theme-notab/blob/master/partials/sidebar.handlebars#L11

But it doesn't work for properties and methods link (sidebar-members)：
https://github.com/fireball-x/firedoc-theme-notab/blob/master/partials/sidebar-members.handlebars#L9

In one of those sidebar-member template, I can get one level of parent correctly `{{../this}}` will return module context correctly, but `{{../../this}}` will not go up any further.

So I cannot get `view.base` from sidebar-member template. Any idea how to get around this?

**Comment by yorkie** [comment]
try this one `{{../../view.base}}`?

**Comment by nantas** [comment]
nah, in sidebar-member template it can only go up one level, `../this` and `../../this` point to the same parent context.

**Comment by nantas** [comment]
ok, a tad more research shows me the discussion on handlebars issues:

https://github.com/wycats/handlebars.js/pull/182
https://github.com/wycats/handlebars.js/pull/392

This problem has been confirmed long ago and the solution is to use `@root` from partial template to get the context of where the template starts rendering, you can search `@root` in this API reference doc:

http://handlebarsjs.com/reference.html

I've updated the #10 to fix sidebar member links.

**Comment by nantas** [comment]
sidebar link updating issue is located, see discussion in https://github.com/fireball-x/firedoc-theme-notab/pull/10#issuecomment-155994909
